function applyResearchStyle(ax)
%APPLYRESEARCHSTYLE Apply a simple readable style to research plots.

if nargin < 1 || isempty(ax)
    ax = gca;
end

set(ax, ...
    "FontName", "Arial", ...
    "FontSize", 11, ...
    "LineWidth", 1.0, ...
    "Box", "on", ...
    "XGrid", "on", ...
    "YGrid", "on");
end

