%EX01_MAT_CSV_TEXT_IO Demonstrate small MAT, CSV, and TXT files.

clear; clc; close all;
learningRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(learningRoot);
addpath(fullfile(learningRoot, "functions"));
addpath(fullfile(learningRoot, "data", "external_paths"));
rootDir = startup_learning;

demo = fusionlearn.io.makeDemoSignal("DurationMs", 5, "SampleRateHz", 20000);
outputDir = fullfile(rootDir, "data", "simulated");
if ~isfolder(outputDir)
    mkdir(outputDir);
end

matFile = fullfile(outputDir, "example_io_signal.mat");
save(matFile, "demo");
fusionlearn.io.checkMatFileInfo(matFile);

csvFile = fullfile(outputDir, "example_io_signal_first50.csv");
signalTable = table(demo.time_ms(1:50), demo.signal(1:50), ...
    'VariableNames', ["time_ms", "signal"]);
writetable(signalTable, csvFile);

txtFile = fullfile(outputDir, "example_io_notes.txt");
writelines(["MAT/CSV/TXT example"; "Generated by ex01_mat_csv_text_io.m"], txtFile);

assert(isfile(matFile));
assert(isfile(csvFile));
assert(isfile(txtFile));
